# Generated by Django 5.0.7 on 2024-07-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_rename_content_devtool_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ideas/')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea')),
            ],
        ),
    ]
