# Generated by Django 5.0.7 on 2024-07-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_ideastar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideastar',
            name='user',
        ),
    ]
