# Generated by Django 5.0.7 on 2024-07-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_remove_ideastar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='image',
        ),
    ]
