# Generated by Django 5.0.7 on 2024-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_remove_idea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
