# Generated by Django 5.0.7 on 2024-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_ideaimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
