# Generated by Django 5.0.7 on 2024-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlist',
            name='actor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewlist',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewlist',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
