# Generated by Django 5.0.7 on 2024-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0002_reviewlist_actor_reviewlist_director_reviewlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlist',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
