# Generated by Django 5.0.7 on 2024-07-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_alter_reviewlist_actor_alter_reviewlist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlist',
            name='image',
        ),
        migrations.AddField(
            model_name='reviewlist',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
