# Generated by Django 5.0.7 on 2024-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0005_remove_reviewlist_image_reviewlist_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlist',
            name='imgfile',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
