# Generated by Django 5.0.7 on 2024-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0006_alter_reviewlist_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlist',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='reviewlist',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
